name: Rebel Finance
favicon: null
layout_spectrum: 0.41385
typography_spectrum: 0.3221485677640885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#004865'
    - '#00263e'
    - '#f3f7f8'
    - '#6ca1c5'
    - '#b6d1e0'
  brandStrength: 0.5985842251684517
  lightness: 0.875
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
